### ISSUE TITLE
please add license :-)

### ISSUE THREAD

**Issue by amitu** [jonathanhefner/elm-range#1]

**Comment by jonathanhefner** [comment]
I discontinued this project because there was (is?) a lengthy approval process for libraries to be published to the official Elm repo if they include JavaScript native code, which this library does.

I haven't kept up with Elm at all since then.  Do you have a particular use for this library?

**Comment by amitu** [comment]
Coming from python I use range a lot. Did not realise it was using native code, should not have to I suppose.

**Comment by jonathanhefner** [comment]
Closing this out, but I wanted to cross-reference the relevant failed attempt to publish this package: elm-lang/package.elm-lang.org#18

See my comment there as to why this library uses JavaScript native code.  Like I said, I haven't kept up with Elm since, but if / when Elm gets proper tail call optimization (TCO), this library could be re-written in pure Elm.
